plugins { id 'java'; id 'application' }
group = 'com.lodeen'; version = '0.1.0'
repositories { mavenCentral() }
ext { lwjglVersion = '3.3.3'; jomlVersion = '1.10.5' }

dependencies {
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")
    implementation "org.lwjgl:lwjgl", "org.lwjgl:lwjgl-glfw", "org.lwjgl:lwjgl-opengl"
    implementation "org.joml:joml:$jomlVersion"

    def os = System.getProperty('os.name').toLowerCase()
    def natives = os.contains('win') ? 'natives-windows'
                : os.contains('mac') ? 'natives-macos' : 'natives-linux'
    ['lwjgl','lwjgl-glfw','lwjgl-opengl'].each {
        runtimeOnly "org.lwjgl:$it::$natives"
    }
}
application { mainClass = 'com.lodeen.Main' }
java { sourceCompatibility = JavaVersion.VERSION_17; targetCompatibility = JavaVersion.VERSION_17 }
