apiVersion: v1
kind: Service
metadata:
  name: lodeen-server
  namespace: lodeen
  labels:
    app: lodeen-server
spec:
  type: ClusterIP
  selector:
    app: lodeen-server
  ports:
    - name: tcp-game
      port: 7777
      targetPort: tcp-game
    - name: admin
      port: 9091
      targetPort: admin
