apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lodeen-server
  namespace: lodeen
  labels:
    app: lodeen-server
spec:
  ingressClassName: traefik
  rules:
    - host: lodeen.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lodeen-server
                port:
                  number: 9091
