apiVersion: v1
kind: Service
metadata:
  name: {{ include "lodeen.fullname" . }}-headless
  labels:
    {{- include "lodeen.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "lodeen.selectorLabels" . | nindent 4 }}
  ports:
    - name: tcp-game
      port: {{ .Values.service.gamePort }}
      targetPort: tcp-game
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
